name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v2
      with:
        cmake-version: 3.20

    - name: Create build directory
      run: mkdir build
      working-directory: ./

    - name: Configure CMake
      run: cmake -Bbuild -S. -DCMAKE_BUILD_TYPE=Release
      working-directory: ./

    - name: Build project
      run: cmake --build build --config Release
      working-directory: ./
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: cmake --build build --target test
      working-directory: ./
